services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/credishop_development
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
    networks:
      - internal

  postgres:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: credishop_development
    networks:
      - internal

  redis:
    image: redis:6.2
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "6379:6379"
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  pgdata:
