version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp_development
    networks:
      - internal

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:migrate || (bundle exec rails db:create db:migrate db:seed || echo 'skipping dump error') && bundle exec db:seed && bundle exec rails server -b '0.0.0.0'"
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    networks:
      - internal

volumes:
  pgdata:
    driver: local

networks:
  internal:
    driver: bridge
