default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: credishop_development

test:
  <<: *default
  database: credishop_test

production:
  <<: *default
  database: credishop_production
